# Generated by Django 5.1.2 on 2024-11-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_remove_servicerequest_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_date', models.DateTimeField(blank=True, null=True)),
                ('frequency_time', models.CharField(blank=True, max_length=10, null=True)),
                ('frequency_week', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency_type', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_services', models.JSONField(default=list)),
                ('type_of_construction', models.CharField(max_length=50)),
                ('bedrooms_number', models.PositiveIntegerField()),
                ('bathrooms_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('accept_terms', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado')], default='pending_payment', max_length=20)),
            ],
        ),
    ]
