# Generated by Django 5.1.2 on 2024-11-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicestatus',
            name='service_request',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.DeleteModel(
            name='ServiceStatus',
        ),
    ]
